name: Task
description: A structured task created during planning. Scoped to be completable in a single agent session.
title: ""
labels: ["task"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done and why.
      placeholder: Describe the task in 1-3 sentences.
    validations:
      required: true

  - type: textarea
    id: files-to-modify
    attributes:
      label: Files to modify
      description: List all files that should be created or changed for this task.
      placeholder: |
        - path/to/file1.ts
        - path/to/file2.ts
      render: markdown
    validations:
      required: true

  - type: textarea
    id: implementation-steps
    attributes:
      label: Implementation steps
      description: Ordered steps to complete the task. Each step should be concrete and verifiable.
      placeholder: |
        1. First step
        2. Second step
        3. Third step
      render: markdown
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Conditions that must be true for this task to be considered complete.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
      render: markdown
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Other issues that must be completed before this task can start. Use issue references.
      placeholder: |
        Blocked by #XX, #YY
    validations:
      required: false
